# Generated by Django 4.2 on 2023-05-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3)),
                ('charged', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_réservation.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_réservation.vehicle')),
            ],
        ),
    ]
